### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by Trainmaster**

### CODE REVIEW

**Comment by 1ma** [comment]
Sorry to ask here, but the issue tab is disabled for this repo and this is tangentially related: could we make the 2.x releases available in PECL? https://pecl.php.net/package/gearman

**Comment by SteffenAnders** [comment]
What is the status here?

In order to run GearmanClient under PHP 7.4 I have to check out the master branch and build the PHP extension from it.

Is it at least possible to create a GIT tag for version 2.0.7? A PECL release would be even better. :)

**Comment by SteffenAnders** [comment]
ping @jedi-pl @wcgallego

**Comment by wcgallego** [comment]
hi @SteffenAnders, appreciate the ping and wanting to move here. I'm unfortunately no longer maintaining this and haven't since it was moved to this new repo. It may be in search of a proper maintainer for long term caretaking

**Comment by jedi-pl** [comment]
@SteffenAnders I am not the maintainer either :) 
However you can look here. 
It's my private temporary solution for this problem: https://github.com/jedi-pl/pecl-networking-gearman/releases/tag/2.0.7

**Comment by andypost** [comment]
Btw in a light of PHP 8 - any idea how much work it needs to port to?

**Comment by SteffenAnders** [comment]
@andypost thanks mate, that was also my plan (in the worst case) :P

@rlerdorf @keyurdg @xalopp @muzki  what about the other "active" contributors, is anyone able to make an official 2.0.7 release based on current master (including the PHP 7.4 bugfix)?

**Comment by rlerdorf** [comment]
There will be a 2.1.0 release shortly. I cleaned up a bunch of stuff and added PHP 8.0 support.

**Comment by oleg-st** [comment]
2.1.0 has been released
I think we can close this PR

**Pull request closed without merging**
