### PR TITLE
Fix 8.0 compatibility

### PR DESCRIPTION
**Pull request by andypost**
- replace `call_user_function_ex()` with `call_user_function()` ref https://github.com/php/php-src/commit/302933daea77663f5759b10accd1d0231393b24c
- TODO fix `ZEND_ACC_DTOR` replace https://github.com/php/php-src/commit/08c5c69eff6f0110b373c55ee2246591d14cc82b

### CODE REVIEW

**Comment by andypost** [comment]
The only warning left
```
/mnt/pecl-networking-gearman/php_gearman.c:69:24: warning: 'arginfo_gearman_task_context' defined but not used [-Wunused-const-variable=]
   69 | ZEND_BEGIN_ARG_INFO_EX(arginfo_gearman_task_context, 0, 0, 1)
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/php8/Zend/zend_API.h:161:38: note: in definition of macro 'ZEND_BEGIN_ARG_INFO_EX'
  161 |  static const zend_internal_arg_info name[] = { \
      |                                      ^~~~
```
and tests now
```
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   13
---------------------------------------------------------------------

Number of tests :   61                42
Tests borked    :    6 (  9.8%) --------
Tests skipped   :   13 ( 21.3%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :   17 ( 27.9%) ( 40.5%)
Tests passed    :   25 ( 41.0%) ( 59.5%)
---------------------------------------------------------------------
Time taken      :    1 seconds
...
FAILED TEST SUMMARY
---------------------------------------------------------------------
GearmanClient::addServer(), gearman_client_add_server() [tests/gearman_client_012.phpt]
GearmanClient::addServers(), gearman_client_add_servers() [tests/gearman_client_013.phpt]
GearmanClient::wait(), gearman_client_wait() [tests/gearman_client_014.phpt]
GearmanClient::doJobHandle(), gearman_client_do_job_handle() [tests/gearman_client_015.phpt]
GearmanClient::doStatus(), gearman_client_do_status() [tests/gearman_client_016.phpt]
GearmanClient::jobStatus(), gearman_client_job_status() [tests/gearman_client_017.phpt]
GearmanClient::jobStatusByUniqueKey(), gearman_client_job_status_by_unique_key() [tests/gearman_client_018.phpt]
GearmanClient::ping(), gearman_client_ping() [tests/gearman_client_019.phpt]
GearmanClient::clearCallbacks(), gearman_client_clear_callbacks() [tests/gearman_client_020.phpt]
 [tests/gearman_client_integration_test_001.phpt]
GearmanClient::setStatusCallback(), gearman_client_set_status_callback(),
GearmanClient::addTaskStatus(), gearman_client_add_task_status(),
GearmanClient::runTasks(), gearman_client_run_tasks() [tests/gearman_client_integration_test_002.phpt]
GearmanTask::functionName, gearman_task_function_name [tests/gearman_task_001.phpt]
GearmanTask::unique, gearman_task_unique [tests/gearman_task_002.phpt]
GearmanTask::jobHandle(), gearman_task_job_handle() [tests/gearman_task_003.phpt]
GearmanTask::is_known(), gearman_task_is_known(),
GearmanTask::is_running(), gearman_task_is_running(),
GearmanTask::numerator(), gearman_task_numerator(),
GearmanTask::denominator(), gearman_task_denominator() [tests/gearman_task_004.phpt]
GearmanTask::data(), gearman_task_data(),
GearmanTask::dataSize(), gearman_task_data_size() [tests/gearman_task_005.phpt]
gearman_worker_wait() [tests/gearman_worker_011.phpt]
```

**Comment by oleg-st** [comment]
I created the fork with PHP 8 support and some other fixes
https://github.com/oleg-st/pecl-networking-gearman

**Comment by rlerdorf** [comment]
@oleg-st @andypost sorry, I didn't even notice this issue before working on the 8.0 support today with proper arginfo generated from stubs - https://github.com/php/pecl-networking-gearman/blob/master/gearman.stub.php with the appropriate backward compatibility macros to compile on PHP 7.3 and 7.4 as well.
@oleg-st any chance you could re-work your work against this and send me a PR for the changes you made beyond just the 8.0 support?

**Comment by andypost** [comment]
@rlerdorf thank you a lot for note, rebased and there's only 2 places could be commited

Meantime used to build from commit 26a84800401e51a7f3993271168e721500a3729f and found the only missing feature - ability to skip online tests

**Comment by oleg-st** [comment]
@rlerdorf sure

**Comment by oleg-st** [comment]
@rlerdorf 

test `gearman_client_003.phpt` fails with error:
```
Fatal error: GearmanClient::error(): Return value must be of type string, bool returned in Unknown on line 0
```

It looks like it can return false if there are no errors

**Comment by rlerdorf** [comment]
the `GearmanClient::error()` return type should be fixed now

**Comment by rlerdorf** [comment]
@andypost you mean a way to skip tests if you don't have access to a gearmand? What do you think the best way to do that would be? Run a `ps | grep gearmand` in a shell script or something and `skip` if it isn't running?
I am also not quite sure what you meant by there only being 2 places to be committed from your fork. Could you point me to the diff of the missing things?

**Comment by oleg-st** [comment]
> @oleg-st any chance you could re-work your fork against this and send me a PR for the changes you made beyond just the 8.0 support?

Done https://github.com/php/pecl-networking-gearman/pull/4

**Comment by andypost** [comment]
@rlerdorf I mean this PR, I used to rebase it on top of master and it shows diff for 2 "closing code comments'

**Comment by andypost** [comment]
Filed PR #5 to resolve connection issues in tests and fix remaining TODOs

**Comment by rlerdorf** [comment]
I think these have all been taken care of now. Thanks for the help. I'll close this.

**Pull request closed without merging**
